from rand import Rand

class Names(object):
    # Baby names for 1990 http://www.ssa.gov/OACT/babynames/#&ht=1

    given_names = [
        ["Michael","Jessica"],
        ["Christopher","Ashley"],
        ["Matthew","Brittany"],
        ["Joshua","Amanda"],
        ["Daniel","Samantha"],
        ["David","Sarah"],
        ["Andrew","Stephanie"],
        ["James","Jennifer"],
        ["Justin","Elizabeth"],
        ["Joseph","Lauren"],
        ["Ryan","Megan"],
        ["John","Emily"],
        ["Robert","Nicole"],
        ["Nicholas","Kayla"],
        ["Anthony","Amber"],
        ["William","Rachel"],
        ["Jonathan","Courtney"],
        ["Kyle","Danielle"],
        ["Brandon","Heather"],
        ["Jacob","Melissa"],
        ["Tyler","Rebecca"],
        ["Zachary","Michelle"],
        ["Kevin","Tiffany"],
        ["Eric","Chelsea"],
        ["Steven","Christina"],
        ["Thomas","Katherine"],
        ["Brian","Alyssa"],
        ["Alexander","Jasmine"],
        ["Jordan","Laura"],
        ["Timothy","Hannah"],
        ["Cody","Kimberly"],
        ["Adam","Kelsey"],
        ["Benjamin","Victoria"],
        ["Aaron","Sara"],
        ["Richard","Mary"],
        ["Patrick","Erica"],
        ["Sean","Alexandra"],
        ["Charles","Amy"],
        ["Stephen","Crystal"],
        ["Jeremy","Andrea"],
        ["Jose","Kelly"],
        ["Travis","Kristen"],
        ["Jeffrey","Erin"],
        ["Nathan","Brittney"],
        ["Samuel","Anna"],
        ["Mark","Taylor"],
        ["Jason","Maria"],
        ["Jesse","Allison"],
        ["Paul","Cassandra"],
        ["Dustin","Caitlin"],
        ["Gregory","Lindsey"],
        ["Kenneth","Angela"],
        ["Scott","Alicia"],
        ["Derek","Jamie"],
        ["Austin","Katie"],
        ["Corey","Vanessa"],
        ["Bryan","Kathryn"],
        ["Ethan","Morgan"],
        ["Alex","Jordan"],
        ["Christian","Whitney"],
        ["Juan","Brianna"],
        ["Cameron","Christine"],
        ["Jared","Natalie"],
        ["Taylor","Lisa"],
        ["Bradley","Kristin"],
        ["Luis","Alexis"],
        ["Cory","Jacqueline"],
        ["Edward","Shannon"],
        ["Shawn","Lindsay"],
        ["Ian","Brooke"],
        ["Evan","Catherine"],
        ["Marcus","Olivia"],
        ["Shane","April"],
        ["Peter","Erika"],
        ["Carlos","Katelyn"],
        ["Trevor","Monica"],
        ["Antonio","Kristina"],
        ["Vincent","Kaitlyn"],
        ["George","Paige"],
        ["Keith","Molly"],
        ["Phillip","Jenna"],
        ["Victor","Leah"],
        ["Dylan","Julia"],
        ["Brett","Bianca"],
        ["Chad","Tara"],
        ["Nathaniel","Melanie"],
        ["Donald","Marissa"],
        ["Caleb","Cynthia"],
        ["Casey","Holly"],
        ["Jesus","Abigail"],
        ["Blake","Meghan"],
        ["Raymond","Kathleen"],
        ["Mitchell","Julie"],
        ["Adrian","Ariel"],
        ["Joel","Alexandria"],
        ["Erik","Veronica"],
        ["Ronald","Patricia"],
        ["Devin","Diana"],
        ["Garrett","Gabrielle"],
        ["Gabriel","Shelby"]
    ]

    n_given_names = given_names.__len__()


    # https://en.wikipedia.org/wiki/List_of_most_common_surnames_in_North_America#United_States

    family_names = [
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Miller",
        "Davis",
        "Garcia",
        "Rodriguez",
        "Wilson",
        "Martinez",
        "Anderson",
        "Taylor",
        "Thomas",
        "Hernandez",
        "Moore",
        "Martin",
        "Jackson",
        "Thompson",
        "White",
        "Lopez",
        "Lee",
        "Gonzalez",
        "Harris",
        "Clark",
        "Lewis",
        "Robinson",
        "Walker",
        "Perez",
        "Hall",
        "Young",
        "Allen",
        "Sanchez",
        "Wright",
        "King",
        "Scott",
        "Green",
        "Baker",
        "Adams",
        "Nelson",
        "Hill",
        "Ramirez",
        "Campbell",
        "Mitchell",
        "Roberts",
        "Carter",
        "Phillips",
        "Evans",
        "Turner",
        "Torres",
        "Parker",
        "Collins",
        "Edwards",
        "Stewart",
        "Flores",
        "Morris",
        "Nguyen",
        "Murphy",
        "Rivera",
        "Cook",
        "Rogers",
        "Morgan",
        "Peterson",
        "Cooper",
        "Reed",
        "Bailey",
        "Bell",
        "Gomez",
        "Kelly",
        "Howard",
        "Ward",
        "Cox",
        "Diaz",
        "Richardson",
        "Wood",
        "Watson",
        "Brooks",
        "Bennett",
        "Gray",
        "James",
        "Reye",
        "Cruz",
        "Hughes",
        "Price",
        "Myers",
        "Long",
        "Foster",
        "Sanders",
        "Ross",
        "Morales",
        "Powell",
        "Sullivan",
        "Russell",
        "Ortiz",
        "Jenkins",
        "Gutierrez",
        "Perry",
        "Butler",
        "Barnes",
        "Fisher"
    ]

    n_family_names = family_names.__len__()

    # http://high-schools.com/directory/ny/cities/brooklyn/

    high_school_names = [
        "Abraham Lincoln High School",
        "Academy For College Prep & Career Exploration: A Coll",
        "Academy For Conservation And The Environment",
        "Academy For Environmental Leadership",
        "Academy For Health Careers",
        "Academy For Young Writers",
        "Academy Of Business And Community Development",
        "Academy Of Hospitality And Tourism",
        "Academy Of Innovative Technology",
        "Academy Of Urban Planning",
        "Achievement First Bushwick Charter School",
        "Achievement First Crown Heights Charter School",
        "Achievement First Endeavor Charter School",
        "Acorn Community High School",
        "Ahaba Ve Ahava",
        "Ahrc Middle/high School",
        "Al-madinah School",
        "Al-noor School",
        "All City Leadership Secondary School",
        "Arts And Media Preparatory Academy",
        "Aspirations Diploma Plus High School",
        "Automotive High School",
        "B'not Rachel High School For Girls",
        "Bais Fruma",
        "Bais Rochel School",
        "Bais Rochel School",
        "Bais Sarah-educ School For Girls",
        "Bais Yaakov Academy",
        "Bais Yaakov Oz Vehodor",
        "Bais Yakov Of Khal Adas Yereim",
        "Bais Yitzchak Yeshiva",
        "Bay Ridge Prep",
        "Bay Ridge Preparatory School",
        "Be'er Hagolah Institutes (b & G)",
        "Bedford Academy High School",
        "Bedford Stuyvesant Collegiate Charter School",
        "Bedford Stuyvesant Preparatory High School",
        "Beis Chaya Mushka",
        "Believe Northside Charter High School",
        "Believe Southside Charter High School",
        "Benjamin Banneker Academy",
        "Bet Yaakov Ateret Torah",
        "Bet Yaakov Orot Sarah",
        "Beth Chana School",
        "Beth Jacob High School",
        "Beth Rivka High School",
        "Bible Speak Church Academy",
        "Bishop Ford Central Catholic High School",
        "Bishop Kearney High School",
        "Bishop Loughlin Memorial High School",
        "Bnei Shimon Yisroel",
        "Bnos Chayil",
        "Bnos Chomesh Academy",
        "Bnos Margulia Viznitz",
        "Bnos Menachem",
        "Bnos Yaakov",
        "Bnos Yakov School For Girls",
        "Bnos Yerushalayim School",
        "Bnot Chaya Academy",
        "Bonim Lamokom",
        "Boys And Girls High School",
        "Brooklyn Academy High School",
        "Brooklyn Academy Of Science And The Environment",
        "Brooklyn Amity School",
        "Brooklyn Autism Center Academy",
        "Brooklyn Bridge Academy",
        "Brooklyn College Academy",
        "Brooklyn Collegiate-a College Board School",
        "Brooklyn Community High School-communication, Arts &",
        "Brooklyn Democracy Academy",
        "Brooklyn Free School",
        "Brooklyn Friends School",
        "Brooklyn Frontiers High School",
        "Brooklyn Generation School",
        "Brooklyn High School For Law And Technology",
        "Brooklyn High School For Leadership And Community",
        "Brooklyn High School Of The Arts",
        "Brooklyn Institute For Liberal Arts",
        "Brooklyn International High School At Waters Edge",
        "Brooklyn Lab School",
        "Brooklyn Latin School (the)",
        "Brooklyn Preparatory High School",
        "Brooklyn Prospect Charter School",
        "Brooklyn School For Global Studies",
        "Brooklyn School For Math And Research",
        "Brooklyn School For Music & Theater",
        "Brooklyn Secondary School For Collaborative Studie",
        "Brooklyn Studio Secondary School",
        "Brooklyn Technical High School",
        "Brooklyn Theatre Arts High School",
        "Brownsville Academy High School",
        "Brownsville Collegiate Charter School",
        "Bushwick Community High School",
        "Bushwick Leaders High School For Academic Excellence",
        "Bushwick School For Social Justice",
        "Carmel Christian School",
        "Catherine Mc Auley High School",
        "Central Uta",
        "Christian Heritage Academy",
        "City Polytechnic High School Of Engineering, Archi",
        "Clara Barton High School",
        "Cobble Hill School Of American Studies",
        "Congregation Biz Dushinsky",
        "Congregation Machne Shalva",
        "Cultural Academy For The Arts And Sciences",
        "Cypress Hills Collegiate Preparatory School",
        "Darchai Menachem School-boys",
        "Darkei Tshivo Of Dinov",
        "Dr Susan S Mckinney Secondary School Of The Arts",
        "Eagle Academy For Young Men Ii",
        "East Brooklyn Community High School",
        "East New York Family Academy",
        "Ebc High School For Public Service-bushwick",
        "Educational Institute Oholei Torah-oholei Menachem",
        "Edward R Murrow High School",
        "El Puente Academy For Peace And Justice",
        "Elite High School",
        "Excellence Boys Charter School Of Bedford Stuyvesa",
        "Excelsior Elementary School",
        "Expeditionary Learning School For Community Leader",
        "Fdny High School For Fire And Life Safety",
        "Followers Of Jesus School",
        "Fontbonne Hall Academy",
        "Fort Hamilton High School",
        "Foundations Academy",
        "Frances Perkins Academy",
        "Franklin Delano Roosevelt High School",
        "Franklin K Lane High School",
        "Frederick Douglass Academy Iv Secondary School",
        "Frederick Douglass Academy Vii High School",
        "Freedom Academy High School",
        "George Westinghouse Career & Technical Ed High School",
        "Gesher Yehuda",
        "Gotham Professional Arts Academy",
        "Green School: An Academy For Environmental Careers",
        "Hasc - Hebrew Academy For Special Children",
        "High School For Civil Rights",
        "High School For Global Citizenship (the)",
        "High School For Innovation In Advertising And Medi",
        "High School For Medical Professions",
        "High School For Service And Learning At Erasmus",
        "High School For Youth And Community Development",
        "High School Of Enterprise, Business & Technology",
        "High School Of Sports Management",
        "High School Of Telecommunications Arts And Technol",
        "High School For Public Service-heroes Of Tomorrow",
        "Hychel Hatorah Of Williamsburg",
        "Imagine Academy",
        "International Arts Business School",
        "International Christian School",
        "International High School At Lafayette",
        "International High School At Prospect Heights",
        "It Takes A Village Academy",
        "James Madison High School",
        "Jewish Center For Special Educ",
        "Jhs 296 The Anna Gonzalez Community School",
        "John Dewey High School",
        "Joseph S Gruss Yeshiva High School",
        "Juan Morel Campos Secondary School",
        "Keren Hatorah",
        "Khalil Gibran International Academy",
        "Kings Collegiate Charter School",
        "Kingsborough Early College School",
        "Kipp Amp Charter School",
        "Kurt Hahn Expeditionary Learning School",
        "League School",
        "Leon M Goldstein High School For The Sciences",
        "Lev Bais Yaakov",
        "Liberation Diploma Plus",
        "Life Academy High School For Film And Music",
        "Lubavitcher High School",
        "Lyons Community School",
        "Machon Bais Yaakov Hilda Birn High School",
        "Machon Chana",
        "Mary Mcdowell Friends School",
        "Masores Bais Yaakov",
        "Medgar Evers College Preparatory School",
        "Mesivta High School",
        "Mesivta Imrei Yosef Spinka",
        "Mesivta Lev Bonim",
        "Mesivta M'kor Chaim School",
        "Mesivta Nachlas Yakov School",
        "Mesivta Yeshiva Rabbi Chaim Berlin",
        "Metropolitan Corporate Academy High School",
        "Metropolitan Diploma Plus High School",
        "Middle School For The Arts",
        "Midwood High School",
        "Millennium Brooklyn High School",
        "Mirrer Yeshiva High School",
        "Mosdos Chasidei Square",
        "Mt Pleasant Christian Academy",
        "Multicultural High School",
        "Nazareth Regional High School",
        "Nefesh Academy",
        "Nesivos Bais Yaakov",
        "New Dawn Charter High School",
        "New Utrecht High School",
        "New Vistas Academy",
        "Nysarc- Nyc Chapter",
        "Ohr Halimud - The Multi Sensory Learning Center",
        "Olympus Academy",
        "Pacific High School",
        "Park Slope Collegiate",
        "Pathways Technology Early College High School",
        "Paul Robeson High School",
        "Performing Arts And Technology High School",
        "Poly Prep Country Day School",
        "Progress High School For Professional Careers",
        "Prospect Park Bnos Leah High School",
        "Ps 141",
        "Ps 36",
        "Ps 368",
        "Ps 369 Coy L Cox School",
        "Ps 370",
        "Ps 371 Lillian L Rashkis",
        "Ps 373 Brooklyn Transition Center",
        "Ps 53",
        "Ps 721 Brooklyn Occupational Training Center",
        "Ps 753 School For Career Development",
        "Ps 77",
        "Ps 771",
        "Ps 811 Connie Lekas School",
        "Rachel Carson High School For Coastal Studies",
        "Reach For The Stars Learning Center",
        "Roads Charter School 1",
        "Satellite Three",
        "Scholar Skills Christian Academy",
        "School For Classics: An Academy Of Thinkers, Writ",
        "School For Democracy And Leadership",
        "School For Human Rights (the)",
        "School For International Studies",
        "School For Legal Studies",
        "Science Skills Center High School For Sci, Tech An",
        "Science, Tech & Research High School At Erasmus",
        "Secondary School For Journalism",
        "Secondary School For Law",
        "Shaare Torah High School-girls",
        "Sheepshead Bay High School",
        "Shulamith School For Girls",
        "Sinai Academic Center",
        "South Brooklyn Community High School",
        "St Ann's School",
        "St Edmund Preparatory High School",
        "St Joseph High School",
        "St Saviour High School",
        "Step-special Torah Education Program",
        "Summit Academy Charter School",
        "Sunset Park High School",
        "Talmud Torah Dnitra",
        "Talmud Torah Of Kasho",
        "Talmud Torah Ohel Yochanan",
        "Talmud Torah Tashbar",
        "Talmud Torah Toldos Yakov Yosef",
        "Teachers Preparatory High School",
        "The Brooklyn Academy Of Global Finance",
        "Tiferes Bnos / Cong Ahavaz Shulem Nadverna",
        "Tiferes Miriam School For Girls",
        "Tomer Dvora High School",
        "Torah Academy High School",
        "Transit Tech Career And Technical Education High S",
        "Ucp Brooklyn Childrens Program",
        "Uft Charter School",
        "United Talmudical Academy",
        "Urban Action Academy",
        "Urban Assembly Institute Of Math And Science For Y",
        "Urban Assembly School For Criminal Justice",
        "Urban Assembly School For Law And Justice",
        "Urban Assembly School Of Music And Art At Waters E",
        "Urban Dove Charter School",
        "Victory Collegiate High School",
        "Viznitzer Chaider Tiferes Yisroel",
        "W E B Dubois Academic High School",
        "W H Maxwell Career And Technical Education High School",
        "Walk In Love Christian Academy",
        "West Brooklyn Community High School",
        "William E Grady Career And Technical Education Hig",
        "Williamsburg Charter High School",
        "Williamsburg Collegiate Charter School",
        "Williamsburg High School For Architecture And Desi",
        "Williamsburg Preparatory School",
        "World Academy For Total Community Health",
        "Xaverian High School",
        "Yeshiva & Mesivta Torah Temimah",
        "Yeshiva & Mesivta V'yoel Moshe",
        "Yeshiva & Misivta Tiferes Elimelech",
        "Yeshiva Ahavas Israel Boys",
        "Yeshiva Ateret Torah",
        "Yeshiva Beis Meir (boys)",
        "Yeshiva Beth Hillel Of Williamsburg",
        "Yeshiva Beth Josef Zvi Dushinsky",
        "Yeshiva Birchas Shmuel",
        "Yeshiva Bnos Ahavas Israel",
        "Yeshiva Chsan Sofer",
        "Yeshiva Congregation Toras Yuf",
        "Yeshiva Derech Hatorah",
        "Yeshiva Gedolah Ohr Yisroel",
        "Yeshiva Imrei Phi",
        "Yeshiva Imrei Yosef Spinka",
        "Yeshiva Karlin Stolin",
        "Yeshiva Machzikei Hadas",
        "Yeshiva Meor Hatalmud",
        "Yeshiva Mesivta Arugath Habosem",
        "Yeshiva Mesivta Chernobil",
        "Yeshiva Of Brooklyn Girls Div",
        "Yeshiva Ohr Shraga Veretzky",
        "Yeshiva Shaarei Yosher",
        "Yeshiva Steret Tech Girls High School",
        "Yeshiva Tiferes Elimelech",
        "Yeshiva Vyelipol",
        "Yeshivah Of Flatbush",
        "Yeshivah Of Flatbush Joel Braverman High School",
        "Yeshivat Ohel Torah",
        "Yeshivat Or Hatorah",
        "Yeshivat Shaare Rahamim",
        "Young Women's Leadership School Of Brooklyn",
        "Zvi Dov Roth Academy Of Yeshiva Rambam"
    ]
    
    n_high_school_names = high_school_names.__len__()


    _percent_changed_name = 65
    _percent_preferring_different = 5
    _percent_suffix_jr = 5

    @classmethod
    def get_name(self):
        # 50% male
        if Rand.get(100) < 50:
            gender = "M"
            ng = 0
            prefix = "Mr."
        else:
            gender = "F"
            ng = 1
            prefix = "Ms."
        given_name = self.given_names[Rand.get(self.n_given_names)][ng]
        family_name = self.family_names[Rand.get(self.n_family_names)]
        marital_status = Rand.pick([
            ["S", 70],
            ["M", 20],
            ["D", 10]
        ])
        birth_family_name = "" # Or do we want the family_name?
        suffix = ""
        if gender == "F":
            if marital_status != "S" and Rand.get(100) < self._percent_changed_name:
                birth_family_name = self.family_names[Rand.get(self.n_family_names)]
        else:
            if Rand.get(100) < self._percent_suffix_jr:
                suffix = "Jr."
        if Rand.get(100) < self._percent_preferring_different:
            preferred_given_name = self.given_names[Rand.get(self.n_given_names)][ng]
        else:
            # Do we want blank or the actual name?
            preferred_given_name = ""
        return {
            "prefix": prefix,
            "given_name": given_name,
            "family_name": family_name,
            "suffix": suffix,
            "gender": gender,
            "marital_status": marital_status,
            "birth_given_name": given_name, # don't yet support a different birth given name
            "birth_family_name": birth_family_name,
            "preferred_given_name": preferred_given_name
        }


    @classmethod
    def get_high_school_name(self):
        return self.high_school_names[Rand.get(self.n_high_school_names)]
